name: incheon_knowhow
description: incheon knowhow Flutter project
version: 0.0.5+5

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: any

  cupertino_icons: ^1.0.2

  # business log
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  side_effect_bloc: ^1.0.0

  # di
  get_it: ^7.6.4
  provider: ^6.1.1

  # route
  auto_route: ^7.8.4

  # network
  dio: ^5.3.4
  retrofit: ^4.0.3
  pretty_dio_logger: ^1.3.1

  # model
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  multiple_result: ^5.1.0

  # image
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0

  # storeage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # localization
  easy_localization: ^3.0.3

  # map
  flutter_naver_map: ^1.0.2
  geolocator: ^10.1.0

  # util
  google_fonts: ^6.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  share_plus: ^7.2.1
  app_tracking_transparency: ^2.0.4
  flutter_native_splash: ^2.3.6
  iamport_flutter: ^0.10.13
  carousel_slider: ^4.2.1
  event_bus: ^2.0.0
  flutter_easyloading: ^3.0.5
  highlight_text: ^1.7.0

  # flutter_inappwebview: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: any

  flutter_lints: ^2.0.0

  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.4
  auto_route_generator: ^7.3.2
  mockito: ^5.4.4

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/app_launcher.png
  android_gravity: center
  ios_content_mode: center
  web: false
  android_12:
    color: "#FFFFFF"
    image: assets/images/app_launcher_android_12.png

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/ic_flag.png
    - assets/images/ic_flag_completed.png
    - assets/images/course_complete_badge.png
    - assets/images/thumb_culture.png
    - assets/images/thumb_history.png
    - assets/images/thumb_location.png
    - assets/translations/
