// Mocks generated by Mockito 5.4.4 from annotations
// in incheon_knowhow/test/repository/data_response_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:incheon_knowhow/data/datasource/api_client.dart' as _i3;
import 'package:incheon_knowhow/data/response/data_response.dart' as _i2;
import 'package:incheon_knowhow/domain/model/certification_code.dart' as _i9;
import 'package:incheon_knowhow/domain/model/course.dart' as _i8;
import 'package:incheon_knowhow/domain/model/find_id_result.dart' as _i6;
import 'package:incheon_knowhow/domain/model/token.dart' as _i5;
import 'package:incheon_knowhow/domain/model/user.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataResponse_0<T> extends _i1.SmartFake
    implements _i2.DataResponse<T> {
  _FakeDataResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i3.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.DataResponse<_i5.Token>> login(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [data],
        ),
        returnValue: _i4.Future<_i2.DataResponse<_i5.Token>>.value(
            _FakeDataResponse_0<_i5.Token>(
          this,
          Invocation.method(
            #login,
            [data],
          ),
        )),
      ) as _i4.Future<_i2.DataResponse<_i5.Token>>);

  @override
  _i4.Future<_i2.DataResponse<_i6.FindIdResult>> findUserId(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #findUserId,
          [data],
        ),
        returnValue: _i4.Future<_i2.DataResponse<_i6.FindIdResult>>.value(
            _FakeDataResponse_0<_i6.FindIdResult>(
          this,
          Invocation.method(
            #findUserId,
            [data],
          ),
        )),
      ) as _i4.Future<_i2.DataResponse<_i6.FindIdResult>>);

  @override
  _i4.Future<_i2.DataResponse<_i7.User>> getUserMe() => (super.noSuchMethod(
        Invocation.method(
          #getUserMe,
          [],
        ),
        returnValue: _i4.Future<_i2.DataResponse<_i7.User>>.value(
            _FakeDataResponse_0<_i7.User>(
          this,
          Invocation.method(
            #getUserMe,
            [],
          ),
        )),
      ) as _i4.Future<_i2.DataResponse<_i7.User>>);

  @override
  _i4.Future<_i2.DataResponse<List<_i8.Course>>> findCourse(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #findCourse,
          [data],
        ),
        returnValue: _i4.Future<_i2.DataResponse<List<_i8.Course>>>.value(
            _FakeDataResponse_0<List<_i8.Course>>(
          this,
          Invocation.method(
            #findCourse,
            [data],
          ),
        )),
      ) as _i4.Future<_i2.DataResponse<List<_i8.Course>>>);

  @override
  _i4.Future<_i2.DataResponse<String>> register(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [data],
        ),
        returnValue: _i4.Future<_i2.DataResponse<String>>.value(
            _FakeDataResponse_0<String>(
          this,
          Invocation.method(
            #register,
            [data],
          ),
        )),
      ) as _i4.Future<_i2.DataResponse<String>>);

  @override
  _i4.Future<_i2.DataResponse<String>> updateUserPassword(
    int? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPassword,
          [
            id,
            data,
          ],
        ),
        returnValue: _i4.Future<_i2.DataResponse<String>>.value(
            _FakeDataResponse_0<String>(
          this,
          Invocation.method(
            #updateUserPassword,
            [
              id,
              data,
            ],
          ),
        )),
      ) as _i4.Future<_i2.DataResponse<String>>);

  @override
  _i4.Future<_i2.DataResponse<String>> updateUserPhone(
    int? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPhone,
          [
            id,
            data,
          ],
        ),
        returnValue: _i4.Future<_i2.DataResponse<String>>.value(
            _FakeDataResponse_0<String>(
          this,
          Invocation.method(
            #updateUserPhone,
            [
              id,
              data,
            ],
          ),
        )),
      ) as _i4.Future<_i2.DataResponse<String>>);

  @override
  _i4.Future<_i2.DataResponse<String>> updateUserSchool(
    int? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserSchool,
          [
            id,
            data,
          ],
        ),
        returnValue: _i4.Future<_i2.DataResponse<String>>.value(
            _FakeDataResponse_0<String>(
          this,
          Invocation.method(
            #updateUserSchool,
            [
              id,
              data,
            ],
          ),
        )),
      ) as _i4.Future<_i2.DataResponse<String>>);

  @override
  _i4.Future<_i2.DataResponse<String>> updateJinroAccount(
    int? id,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateJinroAccount,
          [
            id,
            data,
          ],
        ),
        returnValue: _i4.Future<_i2.DataResponse<String>>.value(
            _FakeDataResponse_0<String>(
          this,
          Invocation.method(
            #updateJinroAccount,
            [
              id,
              data,
            ],
          ),
        )),
      ) as _i4.Future<_i2.DataResponse<String>>);

  @override
  _i4.Future<_i2.DataResponse<String>> withdraw(int? id) => (super.noSuchMethod(
        Invocation.method(
          #withdraw,
          [id],
        ),
        returnValue: _i4.Future<_i2.DataResponse<String>>.value(
            _FakeDataResponse_0<String>(
          this,
          Invocation.method(
            #withdraw,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.DataResponse<String>>);

  @override
  _i4.Future<_i2.DataResponse<_i9.CertificationCode>>
      sendEmailCertificationCode(Map<String, dynamic>? data) =>
          (super.noSuchMethod(
            Invocation.method(
              #sendEmailCertificationCode,
              [data],
            ),
            returnValue:
                _i4.Future<_i2.DataResponse<_i9.CertificationCode>>.value(
                    _FakeDataResponse_0<_i9.CertificationCode>(
              this,
              Invocation.method(
                #sendEmailCertificationCode,
                [data],
              ),
            )),
          ) as _i4.Future<_i2.DataResponse<_i9.CertificationCode>>);
}
